<a href="https://colab.research.google.com/github/Alireza414/Decision-Tree/blob/main/Decision_tree_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd


# Create Class a with mean=0, stddev=1
a = np.random.normal(loc=0,scale=1,size=(100,2))
# Create Class a with mean=10, stddev=1
b = np.random.normal(loc=10,scale=1,size=(100,2))
print('1st',a,b)
# Add class a label
a = np.concatenate((a,np.zeros((100,1))),axis=1)
# Add class b label
b = np.concatenate((b,np.zeros((100,1))+1),axis=1)
# c is all data together
c = np.concatenate((a,b))
# shuffle data
np.random.shuffle(c)
# make into dataframe for people that give 75s on exams
df = pd.DataFrame(c,columns=['x','y','labels'])
display(df)
feature_cols = ['x','y']
X = df[feature_cols]
y = df['labels']
import matplotlib.pyplot as plt
plt.scatter(a[:,0],a[:,1])
plt.scatter(b[:,0],b[:,1])

plt.figure(figsize = [15,10])
sns.heatmap(df)


## **Classification tree **

In [ ]:

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

# Visualize Decision Tree

## *Visualizing the decision tree*

In [ ]:
from sklearn import tree
fig = plt.figure(figsize=(30,30))
_ = tree.plot_tree(clf, fontsize=9)

## *Regression tree*

In [ ]:
# Create Decision Tree classifer object
Rgr = DecisionTreeRegressor()

# Train Decision Tree Classifer
Rgr = Rgr.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = Rgr.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))


## *More example using wine dataset*

In [ ]:
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',sep=';')
# X = dataset.data; y = dataset.target
# Take a look
print(df.head(5))
# Data dimensionality (rows, colums)
print(df.shape)
# Data distributing
# df.info()
sns.scatterplot(df['alcohol'], df['chlorides'], hue= df['quality'], s=50)



## *Classification Tree*

In [ ]:
X = df.drop('quality', axis=1)
y = df['quality']# Train and Test splitting of data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
print(clf)

y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Report: \n", metrics.classification_report(y_test, y_pred))
print("Precision = TP/TP+FP \n", "Recall = TP/TP+FN \n", "f1 score = F1 Score = 2*(Recall * Precision) / (Recall + Precision) \n", "Support = Actual number of occurance \n", )
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test, y_pred))


## *Regression tree*

In [25]:
X = df.drop('quality', axis=1)
y = df['quality']# Train and Test splitting of data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

Rgr = DecisionTreeRegressor()
Rgr.fit(X_train, y_train)
print(Rgr)

y_pred = Rgr.predict(X_test)
print(y_pred.shape)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Report: \n", metrics.classification_report(y_test, y_pred))
print("Precision = TP/TP+FP \n", "Recall = TP/TP+FN \n", "f1 score = F1 Score = 2*(Recall * Precision) / (Recall + Precision) \n", "Support = Actual number of occurance \n", )
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test, y_pred))

DecisionTreeRegressor()
(400,)
Accuracy: 0.55
Report: 
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        15
           5       0.61      0.61      0.61       163
           6       0.59      0.54      0.57       167
           7       0.52      0.59      0.55        49
           8       0.00      0.00      0.00         5

    accuracy                           0.55       400
   macro avg       0.29      0.29      0.29       400
weighted avg       0.56      0.55      0.55       400

Precision = TP/TP+FP 
 Recall = TP/TP+FN 
 f1 score = F1 Score = 2*(Recall * Precision) / (Recall + Precision) 
 Support = Actual number of occurance 

Confusion Matrix: 
 [[  0   0   1   0   0   0]
 [  1   0  10   3   1   0]
 [  0  16 100  40   6   1]
 [  0   5  51  91  19   1]
 [  0   0   1  17  29   2]
 [  0   0   0   4   1   0]]


In [ ]:
from sklearn import tree
fig = plt.figure(figsize=(30,30))
_ = tree.plot_tree(Rgr, fontsize=9)


In [ ]:
import numpy as np
from sklearn import ensemble
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import scale
from sklearn.ensemble import (
    BaggingRegressor, RandomForestRegressor, AdaBoostRegressor
)

model = ensemble.BaggingClassifier()
model.fit(X_train, y_train)
print(model)


y_pred = model.predict(X_test) 


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Report: \n", metrics.classification_report(y_test, y_pred))
print("Precision = TP/TP+FP \n", "Recall = TP/TP+FN \n", "f1 score = F1 Score = 2*(Recall * Precision) / (Recall + Precision) \n", "Support = Actual number of occurance \n", )
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test, y_pred))

In [ ]:
model = ensemble.ExtraTreesClassifier()
model.fit(X_train, y_train)
print(model)


y_pred = model.predict(X_test) 


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Report: \n", metrics.classification_report(y_test, y_pred))
print("Precision = TP/TP+FP \n", "Recall = TP/TP+FN \n", "f1 score = F1 Score = 2*(Recall * Precision) / (Recall + Precision) \n", "Support = Actual number of occurance \n", )
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test, y_pred))

In [28]:
model = ensemble.RandomForestClassifier()
model.fit(X_train, y_train)
print(model)

y_pred = model.predict(X_test) 


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Report: \n", metrics.classification_report(y_test, y_pred))
print("Precision = TP/TP+FP \n", "Recall = TP/TP+FN \n", "f1 score = F1 Score = 2*(Recall * Precision) / (Recall + Precision) \n", "Support = Actual number of occurance \n", )
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test, y_pred))

RandomForestClassifier()
Accuracy: 0.7225
Report: 
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        15
           5       0.75      0.82      0.79       163
           6       0.71      0.77      0.74       167
           7       0.64      0.55      0.59        49
           8       0.00      0.00      0.00         5

    accuracy                           0.72       400
   macro avg       0.35      0.36      0.35       400
weighted avg       0.68      0.72      0.70       400

Precision = TP/TP+FP 
 Recall = TP/TP+FN 
 f1 score = F1 Score = 2*(Recall * Precision) / (Recall + Precision) 
 Support = Actual number of occurance 

Confusion Matrix: 
 [[  0   0   1   0   0   0]
 [  0   0  10   5   0   0]
 [  0   0 134  26   3   0]
 [  0   0  31 128   8   0]
 [  0   0   2  20  27   0]
 [  0   0   0   1   4   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
